dist: xenial
sudo: required
language: bash
before_install:
  - curl "https://raw.githubusercontent.com/express42/otus-homeworks/2023-03/run.sh" | bash
  - sudo apt-get update
  - sleep 30
  - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
  - sudo python get-pip.py
  - sudo pip install cryptography
  - sudo pip install ansible
  - sudo pip install ansible-lint
  - sudo apt-get install unzip git -y
  - wget https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip
  - sudo unzip terraform_1.4.6_linux_amd64.zip -d /usr/local/bin
  - wget https://releases.hashicorp.com/packer/1.6.5/packer_1.6.5_linux_amd64.zip
  - sudo unzip -o packer_1.6.5_linux_amd64.zip -d /usr/local/bin
  - curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip && unzip tflint.zip && rm tflint.zip
  - sudo mv tflint /usr/local/bin
  - tflint -v
  - terraform --version
  - packer --version
  - ansible-lint --version
  - /usr/local/bin/packer validate -var-file=packer/variables.json.example packer/app.json
  - /usr/local/bin/packer validate -var-file=packer/variables.json.example packer/db.json
  - cd packer
  - /usr/local/bin/packer validate -var-file=variables.json.example ubuntu16.json
  - /usr/local/bin/packer validate -var-file=variables.json.example immutable.json
  - cd ../terraform/stage && mv backend.tf backend.tf.example && terraform init && terraform validate
  - tflint
  - cd ../prod && mv backend.tf backend.tf.example && terraform init && terraform validate
  - tflint
  - cd ../../ansible
  - ansible-lint playbooks/deploy.yml
  - ansible-lint playbooks/clone.yml
  - ansible-lint playbooks/db.yml
  - ansible-lint playbooks/packer_app.yml
  - ansible-lint playbooks/packer_db.yml
  - ansible-lint playbooks/reddit_app_one_play.yml
  - ansible-lint playbooks/reddit_app_multiple_plays.yml
  - ansible-lint playbooks/users.yml
  - ansible-galaxy install -r environments/stage/requirements.yml
  - ansible-lint playbooks/app.yml --exclude=roles/jdauphant.nginx
  - ansible-lint playbooks/site.yml --exclude=roles/jdauphant.nginx
notifications:
  slack:
    on_success: always # default: change
    on_failure: always
