---
- name: Install required system packages
  hosts: all
  become: true
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: present
        update_cache: true

    - name: Install system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: true
